---
# Input files (using Nextflow ${projectDir} variable)
input: "${projectDir}/example/genotype/example.vcf/chr[20-22].vcf"
covarfile: "${projectDir}/example/covariates.tsv"
phenofile: "${projectDir}/example/phenotype.surv.tsv"

#Variables names
pheno_name: surv_y
covariates: "SEX age_at_baseline"
#study_col: surv_y
time_col: study_days

# Model variables
longitudinal_flag: false
survival_flag: true
linear_flag: false
chunk_flag: true

# Parameters for genetic QC
r2thres: -9
minor_allele_freq: "0.05"
minor_allele_ct: "20"
kinship: "0.177"
ancestry: "EUR"
assembly: "hg19"
#Identifier for the input genotype files - useful to cache results
dataset: "V2_SURV"

# Generate manhattan with result files
mh_plot: true